apiVersion: apps/v1
kind: Deployment
metadata:
  name: wundergraph-deployment
spec:
  selector:
    matchLabels:
      app: wundergraph
  replicas: 2
  template:
    metadata:
      labels:
        app: wundergraph
    spec:
      containers:
      - name: wundergraph
        image: kubernetes-demo
        imagePullPolicy: "Always"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 9991